// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCihgplOLtgARvhX5tiRzHm1V3sU3Psxjg',
    appId: '1:553890448396:android:93ef863f6f1a956d101a29',
    messagingSenderId: '553890448396',
    projectId: 'appnotas-3336f',
    storageBucket: 'appnotas-3336f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8_V9J1JYU828BMMrlo4vhsnMORqdVOVg',
    appId: '1:553890448396:ios:0bb123b74a99f2ab101a29',
    messagingSenderId: '553890448396',
    projectId: 'appnotas-3336f',
    storageBucket: 'appnotas-3336f.firebasestorage.app',
    iosBundleId: 'com.alexis.proyecto.appnotas',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAji8sqpW2sxKEvKwItCzEZak6I01uYngw',
    appId: '1:553890448396:web:b1ad95d96f9e351e101a29',
    messagingSenderId: '553890448396',
    projectId: 'appnotas-3336f',
    authDomain: 'appnotas-3336f.firebaseapp.com',
    storageBucket: 'appnotas-3336f.firebasestorage.app',
    measurementId: 'G-JP8WYTSM5G',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8_V9J1JYU828BMMrlo4vhsnMORqdVOVg',
    appId: '1:553890448396:ios:4a6e207175803ee2101a29',
    messagingSenderId: '553890448396',
    projectId: 'appnotas-3336f',
    storageBucket: 'appnotas-3336f.firebasestorage.app',
    iosBundleId: 'com.example.appnotas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAji8sqpW2sxKEvKwItCzEZak6I01uYngw',
    appId: '1:553890448396:web:61d4d23960dcb9c0101a29',
    messagingSenderId: '553890448396',
    projectId: 'appnotas-3336f',
    authDomain: 'appnotas-3336f.firebaseapp.com',
    storageBucket: 'appnotas-3336f.firebasestorage.app',
    measurementId: 'G-2C1Q400GGD',
  );

}